#!/bin/bash

echo "" > config

FAILURES=
echo "Running tests"
for foo in *.io
do
	echo " - $foo"
	cat "$foo" | "$@" -c config > /dev/null 2>&1
	cmp "$foo.out" "$foo.ok" || { echo "Test $foo failed: $(diff $foo.ok $foo.out)"; echo "WANTED:"; cat -A $foo.ok; echo "RESULT:"; cat -A $foo.out;FAILURES="$foo $FAILURES"; }
	rm "$foo.out"
done

test -n "$FAILURES" && echo "Failed tests: $FAILURES" && exit 1

echo "Tests OK"
