#!/bin/sh

test -f failures && rm failures

echo "Starting tests"
for foo in test/*.lex
do
   echo " - $foo"
   ("$@" -r < "$foo" > /dev/null 2>&1;
    cmp "$foo.out" "$foo.ok" || { echo "Test $foo failed: $(diff $foo.ok $foo.out)"; echo "$foo" >> failures; };
    rm "$foo.out") &
done

wait

test -s failures && echo "Tests failed: $(cat failures)" && exit 1

rm failures 2>/dev/null
echo "Tests passed"
